// https://community.bistudio.com/wiki/enableSaving
// Don't allow saving via menu
enableSaving [false, false];

// set the weather
switch("Weather" call BIS_fnc_getParamValue) do
{
	// https://community.bistudio.com/wiki/setRain
	// https://community.bistudio.com/wiki/setOvercast
	case 1:
	{
		0 setOvercast 0;
		0 setRain 0;
	};
	case 2:
	{
		0 setOvercast 0.7; // it can't rain unless overcast is at least 0.7
		0 setRain 0.3;
	};
	case 3:
	{
		0 setOvercast 0.8;
		0 setRain 0.6;
	};
	case 4:
	{
		0 setOvercast 1;
		0 setRain 1;
	};
};
// https://community.bistudio.com/wiki/forceWeatherChange
forceWeatherChange;


// Wait until ALiVE initializes the tasking module
waitUntil {!isNil "ALIVE_autoGeneratedTasks"};
// Overrides the tasks that C2ISTAR will automatically assign to players
// http://alivemod.com/wiki/index.php/Custom_Blacklists
ALIVE_autoGeneratedTasks = ["MilAssault","MilDefence","CivAssault","Assassination","DestroyInfantry","SabotageBuilding","InsurgencyPatrol","InsurgencyDestroyAssets","Rescue","CSAR"];

// TODO: figure out how to add the alive_tablet to all playable units via SQF script
// right now, it's in the init for all 18 playable units


// add some ACRE radios and ALIVE Tablets to the virtual arsenal box
VIRT_ARSENAL addItemCargo["ALIVE_Tablet", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC343", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC152", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC148", 30];



if (isServer) then {
	execVM "Scripts\ALiVE_combat_support.sqf";
	execVM "diary.sqf";
	execVM "Scripts\EquipmentRefresh.sqf";
};

