// https://community.bistudio.com/wiki/enableSaving
// Don't allow saving via menu
enableSaving [false, false];





// Wait until ALiVE initializes the tasking module
waitUntil {!isNil "ALIVE_autoGeneratedTasks"};
// Overrides the tasks that C2ISTAR will automatically assign to players
// http://alivemod.com/wiki/index.php/Custom_Blacklists
ALIVE_autoGeneratedTasks = ["MilAssault","MilDefence","CivAssault","Assassination","DestroyInfantry","SabotageBuilding","InsurgencyPatrol","InsurgencyDestroyAssets","Rescue","CSAR"];

// TODO: figure out how to add the alive_tablet to all playable units via SQF script
// right now, it's in the init for all 18 playable units


// add some ACRE radios and alive_tablets to the virtual arsenal box
VIRT_ARSENAL addItemCargo["alive_tablet", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC343", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC152", 30];
VIRT_ARSENAL addItemCargo["ACRE_PRC148", 30];



if (isServer) then {
	execVM "ALiVE_combat_support.sqf";
	execVM "diary.sqf";
};

